# -----------------------------------------------------------------------------
# Script Name: step_5_process_barcodes_to_match_rds_file.sh
#
# Description:
#   This Bash script is designed to process and merge barcodes from RDS files
#   with LOY (Loss Of Y chromosome) call data generated by VeloCyto. For each
#   donor/sample pair provided in the input file, the script:
#     1. Extracts specific barcodes from a master barcode table based on donor ID.
#     2. Merges these extracted barcodes with the corresponding LOY call data CSV.
#     3. Utilizes a Python script (merge_rds_barcode.py) within an Apptainer
#        container to perform the merging operation.
#
#   The script is intended to be run as a SLURM batch job, requesting 1 node,
#   150GB memory, and a maximum runtime of 60 hours.
#
# Usage:
#   sbatch step_5_process_barcodes_to_match_rds_file.sh <input_file>
#
#   <input_file>: A file containing pairs of donor/sample identifiers (one per line).
#
# Output:
#   For each donor/sample pair, a merged CSV file containing LOY calls with
#   matched barcodes is generated in the specified output directory.
# -----------------------------------------------------------------------------
#!/bin/bash

#SBATCH --nodes=1
#SBATCH --mem=150G
#SBATCH --time=60:00:00


cat $1 | while read a b
do
grep -w $b onek1k_barcode_table_by_donor_id.csv > ${b}_specific_barcod

file2=/mainfs/ddnb/Ahmed/Data/OneK1K/analysis/merged_LOY_calls/${a}_${b}_LOY_total_calls.csv
output=/mainfs/ddnb/Ahmed/Data/OneK1K/analysis/merged_LOY_calls_with_barcodes2/${b}_LOY_total_calls_withbarcode.csv


module load apptainer

apptainer exec -H $PWD \
--bind /mainfs/ddnb/Ahmed/Data/OneK1K:/mainfs/ddnb/Ahmed/Data/OneK1K \
--bind /mainfs/ddnb/Ahmed/metacells_project_py:/mainfs/ddnb/Ahmed/metacells_project_py \
--bind /mainfs/ddnb/Ahmed/images/copyVAE:/mainfs/ddnb/Ahmed/images/copyVAE \
--bind /mainfs/ddnb/Ahmed/call_mCA_genotype/:/mainfs/ddnb/Ahmed/call_mCA_genotype \
--bind /mainfs/ddnb/Ahmed/Data/OneK1K/analysis:/mainfs/ddnb/Ahmed/Data/OneK1K/analysis \
--unsquash \
/mainfs/ddnb/Ahmed/images/datascience-notebook_latest.sif \
python3 scripts_for_preparing_scRNA-seq_LOY_calls/merge_rds_barcode.py --file1 ${b}_specific_barcod --file2 $file2 --output_file  $output




done
